name: scaffolding_api
description: An Aqueduct application with a database connection, data model and OAuth 2.0 endpoints.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  web: 
    path: ../web

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  angular: ^5.1.0
  angular_router: 2.0.0-alpha+20
  angular_components: ^0.10.1